defaults: &defaults
  macos:
    xcode: 11.3.1
    working_directory: /Users/distiller/project

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum ".circleci/deps-cache-version" }}-{{ checksum "package.json" }}
      - run:
          name: initialize
          command: |
            node --version
            yarn --version
            mkdir ci-artifacts
      - run:
          name: npm-deps
          command: yarn --frozen-lockfile
      - run:
          name: build
          command: yarn react-build
      - run: yarn test
      - run:
          name: lint
          command: yarn lint
          when: always
      - save_cache:
          key: dependency-cache-{{ checksum ".circleci/deps-cache-version" }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - package-lock.json
            - ~/.cache
          when: always
      - store_artifacts:
          path: ci-artifacts/
      - persist_to_workspace:
          root: /Users/distiller
          paths:
            - project

  build-binaries:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller
      - restore_cache:
          key: electron-deps-{{ checksum ".circleci/electron-cache-version" }}
      - run:
          name: build-binaries
          command: |
            git checkout master
            git reset --hard ${CIRCLE_SHA1}
            touch build/.version
            BRANCH=master CIRCLE_BRANCH=master yarn simple-semantic-release-pre
            if [[ "$(cat build/.version)" != "" ]]; then
              yarn tamper-version "$(cat build/.version)-pre" --full
            fi
            yarn tamper-version "$(git rev-parse --short HEAD)"
            yarn dist --publish=never
      - run:
          name: test-binary
          command: |
            USE_MAC_BINARY=true yarn e2e
      - run:
          name: collect-artifacts
          command: |
            cp ~/Library/Logs/MtsDetalizationParser/main.log ci-artifacts/app-log.txt
            (cp dist/*.AppImage ci-artifacts/) || true
            (cp dist/*.exe ci-artifacts/) || true
            (cp dist/*.dmg ci-artifacts/) || true
          when: always
      - save_cache:
          key: electron-deps-{{ checksum ".circleci/electron-cache-version" }}
          paths:
            - ~/.cache
          when: always
      - store_artifacts:
          path: ci-artifacts/

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller
      - restore_cache:
          key: electron-deps-{{ checksum ".circleci/electron-cache-version" }}
      - run:
          name: release
          command: |
            if [[ "${CIRCLE_PROJECT_USERNAME}" == "artemv" ]]; then yarn semantic-release; fi
            if [[ "${PUBLISH_VERSION}" != "" ]]; then
              yarn tamper-version "${PUBLISH_VERSION}" --full
            fi
            yarn dist --publish=always
      - run:
          name: copy-binaries
          command: |
            (cp dist/*.AppImage ci-artifacts/) || true
            (cp dist/*.exe ci-artifacts/) || true
            (cp dist/*.dmg ci-artifacts/) || true
          when: always
      - save_cache:
          key: electron-deps-{{ checksum ".circleci/electron-cache-version" }}
          paths:
            - ~/.cache
          when: always
      - store_artifacts:
          path: ci-artifacts/

workflows:
  version: 2
  main:
    jobs:
      - test:
          context: my npm-based projects
      - build-binaries:
          requires:
            - test
          context: my npm-based projects
          filters:
            branches:
              ignore: master
      - release:
          requires:
            - test
          context: my npm-based projects
          filters:
            branches:
              only: master
